language: go

go:
  - "1.12"

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpcap-dev gcc

script:
  - make all

before_deploy:
  - make package
  - git tag "$(cat VERSION)"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - kubectl-aks.zip
  skip_cleanup: true
  on:
    tag: true
    branch: master