language: go
os: linux
sudo: required
services:
- docker
go:
- 1.11.x
go_import_path: github.com/C123R/kubectl-aks
before_install:
- go get -u github.com/golang/dep/cmd/dep
script:
- make dep
- make
deploy:
  provider: releases
  api_key:
    secure: Ot9VWnxIqLQ29GHIeRb4YXy6nGr51LOkVJJIODTqkwG9+cOcCgBI0zlwKTnMjh5x9Am/0tNZd7vviEMr0PmAH1HjXLkfQUtvEeQf/UKviD0d8JmEunos2uneXa+2elmadjscXI7eXLNBQDwVaLKX7mlKv3Sohu7CxFoa5DX9xEQkliWzDotiIJCMb1CdhvPS8CmrSxnEI7Ucc+6amdtx5cEqw9M9pNiKIN+yUh1fpc1xSzwzxMKXvns8EEZRP+hKH0CmSrG5hihCOzPyyVVX+PjIxwyLs+/cFhtjEqHs+05jlOAqCXNLdDE5KFHmjCmkym2zVOiPEKFR3+w76cWvluN9EuGTlWq4yiACtbPYcnXtGATW6smaUmt7HlbM+lMf/U7ffXpjsvS1GqW1gMXvy5WESu3LWazApKY7VqA/vur/pR7M6TcCyonpj6G7ucitgfsqXVCE/cf9tvdhpmDGH0/lJi0PXZxfkuVy06/Xd+6E6/XY9uUZbyUZbf7M6sKS3BgJauVIxDur8kF6Tb2Ic9QaXTgAPb318LbJ4zMWx4ujo4lCSKpuFqE9PWkLPE9KrqsH8IxCjieOLQ3SqmTO3z2iVW7EkyttvsjJL5JR9dgsAW2D2sruy+QP6N4eXLItzKmo5C0C7nE8WE6ncss4Yh61ZfnzDBlkv9qcNnnIbNw=
  file: release/kubectl-aks-linux-amd64
  on:
    repo: C123R/kubectl-aks
