language: go

go:
  - "1.12"

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpcap-dev gcc

after_success:
  test -n "$TRAVIS_TAG" && curl -s https://raw.githubusercontent.com/goreleaser/get/master/latest | bash


# calls goreleaser
deploy:
- provider: script
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux