language: go
go:
  - "1.12"

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpcap-dev gcc

install:
  - go mod download

after_success:
  test -n "$TRAVIS_TAG" && curl -s https://raw.githubusercontent.com/goreleaser/get/master/latest | bash

deploy:
- provider: script
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  draft: true
  branches:
    only:
    - master
  on:
     tags: true
  condition: $TRAVIS_OS_NAME = linux

notifications:
  email: false